#! /bin/bash

# asdfasdfsf
# echo "  FORKED (pid: 0)"
echo "invalid"
echo "Content-Type: text/plain"
# echo "text/plain"
# echo "Connection: close"
# echo "Content-Length: 99999999999999999999"
# echo "Transfer-Encoding: chunkedxxx"
# echo "asdf: asdf"
# echo "Status: 123 BANANA"
echo ""
echo "Hello world!"
echo ""
echo "All arguments: $0 $@"
echo ""
echo "env:"
echo "$(env)"
echo ""
